### ISSUE TITLE
Webpack creates a corrupted build on production after migrating to V3

### ISSUE THREAD

**Issue by serut** [agraboso/redux-api-middleware#214]
After migrating redux-api-middleware to V3, I get the following issue in the browser console : 

```
Uncaught TypeError: __webpack_require__(...) is not a function
    at eval (union.js_from_dll-reference_core:1)
    at Object../node_modules/lodash/union.js (bundle.js?5c7e9877d72e1fd35872:594)
    at __webpack_require__ (bundle.js?5c7e9877d72e1fd35872:69)
    at eval (ContainerHelper.jsx:4)
    at Module../web_modules/utils/layout/src/ContainerHelper.jsx (bundle.js?5c7e9877d72e1fd35872:5307)
    at __webpack_require__ (bundle.js?5c7e9877d72e1fd35872:69)
```
It happens only when I run the production build, not with the dev or the test build
Our app is pretty big (https://github.com/RegardsOss/regards-frontend ; ~150k code lines), I'm trying to reduce the issue to create a minimal reproduction.

**Comment by serut** [comment]
I switched our DLL compilation to `UMD` instead of the default one `var` and now it works. 
This was a nightmare.

**Comment by serut** [comment]
Ok this is not a nice news, but if I use your lib I can't use DLL anymore.
We can't consider to move DLL to `UMD` as our plugin, another complex system, does not load anymore.

**Comment by serut** [comment]
Thanks for the sample app. I'll check how to reproduce our error on your sample repo.

**Comment by serut** [comment]
Ok that's 5 hours now I'm stuck on this problem. The issue is not easily reproduceable as the problem appears when I load another webpack app in the DOM using `scriptjs`. To explain a little bit more, I have my DLL with React and your dependency, my main app, and many others apps we call plugins that we load in the DOM in an async way.
- The first sick thing is there is no difference between my main app and plugins, but only plugins dies with a `__webpack_require__(...) is not a function` in the console.
- The issue appears with the version 3 and disappear with the version 2.3.0
- If I copy the package (`cp node_modules/redux-api-middleware ./somewhere` ) and remove the line `"browser": "lib/index.umd.js",` the problem disappear

**Comment by serut** [comment]
Ok I found a quick and dirty fix, I use a [Webpack alias](https://webpack.js.org/configuration/resolve/#resolve-alias) to pick the right version of your bundle inside your package.
```
{
    'redux-api-middleware': path.resolve(webappPath, 'node_modules/redux-api-middleware/lib/index.cjs'),
  }
```
It looks like UMD dependencies have some issues with DLL, but that's a Webpack problem so far.
