### ISSUE TITLE
RSAA actions not returning promises.

### ISSUE THREAD

**Issue by NirBenya** [agraboso/redux-api-middleware#179]
From What I understood from the docs, [RSAA] actions should return promises,
But it doesn't seem to be the case since I updated to 2.3.0.

What am I missing?

**Comment by nason** [comment]
Hi @NirBenya can you be more specific or share some sample code demonstrating the issue please?

https://github.com/agraboso/redux-api-middleware/releases/tag/v2.2.0 did change this middleware to prevent it from returning promises on non-RSAA actions

**Comment by NirBenya** [comment]
Hi @nason,
I have and action with the RSAA property, but this does not return a Promise.
this is my code: 

```
 return (dispatch, getState) => {

        const state = getState();
        const token = _.get(state, 'user.csrfToken');

        return dispatch({
            [RSAA]: {
                ...options,
                endpoint: `${API_URL}/${options.endpoint}`,
                credentials: 'include',
                headers: {
                    'X-CSRFToken': token,
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-Client': 'web'
                }
            }
        })
    }
```

**Comment by NirBenya** [comment]
[SOLVED]
The problem was in my middlewares:
I needed redux thunk to come first.

before: 
const middlewares = [logicMiddleware, apiMiddleware, thunkMiddleware];
after:
const middlewares = [thunkMiddleware, apiMiddleware, logicMiddleware ];

**Comment by oliverbienert** [comment]
Changing the order of middlewares did not help in my case:
```
export const loadProject = (id, {duplicate=false, setAuthHeader=true, pathname="projects"} = {}) => {
  return (dispatch) => {
    const headers = {
      "Content-Type": "application/json"
    };
    if (setAuthHeader) {
      const token = localStorage.getItem('token') || null;
      headers.Authorization = `JWT ${token}`;
    }
    dispatch({
      [CALL_API]: {
        endpoint: `/api/${pathname}/${id}/`,
        headers: headers,
        method: "GET",
        types: [
          "PROJECT_REQUEST",
          {
            type: "LOAD_PROJECT_SUCCESS",
            payload: (action, state, res) => {
              return getJSON(res).then((json) => {
                dispatch(setProp("hidemap", true));
                dispatch(resetContent());
                if (pathname === "published-projects") {
                  json.data.mapbox.modus = "content";
                  json.data.mapbox.isEditable = false;
                }
                if (pathname !== "published-projects" && setAuthHeader)
                  dispatch(fetchStyles());
                return {project: json, duplicate: duplicate};
              });
            }
          },
          "PROJECT_FAILURE"
        ]
      }
    }).then(() => dispatch(ActionCreators.clearHistory()));
  };
};
```
The 'clearHistory' action is dispatched with version 1.0.3.
However, when I upgrade to 2.3 and change the symbol to [RSAA], it stops working, so it seems no promise is returned?

**Comment by NirBenya** [comment]
@oliverbienert , but do you see any errors in the console? if the action doesnt return a promise, it should throw an error like: (...).then is not a function.

**Comment by oliverbienert** [comment]
Sorry, it was too late when I posted this. I looked at the wrong place. I have a non RSAA action where I use the returned promise to dispatch another action:
```
export const initLayers = value => {
  return dispatch => {
    dispatch({
      type: INIT_LAYERS,
      value
    }).then(() => dispatch(ActionCreators.clearHistory()));
  };
};
```
After upgrading, an error is thrown, as expected:
```
Uncaught TypeError: dispatch(...).then is not a function
```
So I have to find another way to chain actions.

**Comment by oliverbienert** [comment]
Simple solution: As `dispatch` is synchronous by default, I can simply write:
```
export const initLayers = value => {
  return dispatch => {
    dispatch({
      type: INIT_LAYERS,
      value
    });
    dispatch(ActionCreators.clearHistory());
  };
};
```
And when I need it with an asynchronous RSAA action, I can still use the returned promise.

**Comment by KrzysztofMadejski** [comment]
What would be the typescript for Dispatch that supports Promises?

**Comment by iamandrewluca** [comment]
@KrzysztofMadejski Please elaborate more. It's not clear, what exactly you want to do. Maybe this can help https://github.com/agraboso/redux-api-middleware/issues/256
